<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-21 17:53
=======
# Generated by Django 4.0.5 on 2022-06-21 17:51
>>>>>>> 7e1d949 (feat: show most borrowed book :sparkles: (#10))
=======
# Generated by Django 4.0.5 on 2022-06-21 17:51
=======
# Generated by Django 4.0.5 on 2022-06-21 17:49
>>>>>>> 8877258 (fix: borrow book in favorite :white_check_mark:)
>>>>>>> 6ef9058 (fix: borrow book in favorite :white_check_mark:)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20220621_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
